"""The edit log: the single ordered record of committed edits.

Both code generation and project save/load derive from this one structure, so what the
user sees, the exported script, and the saved project can never disagree.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from figmint.core.commands import Command

PROJECT_SCHEMA = 1


class EditLog:
    """Serializes an ordered list of active commands to code / project JSON.

    Build one from the current undo stack (see
    :meth:`figmint.core.history.CommandStack.make_editlog`) so the exported code and
    saved project always match what the user currently sees — undone edits are excluded.
    """

    def __init__(self, commands: list[Command] | None = None) -> None:
        self._commands: list[Command] = list(commands) if commands else []

    def __len__(self) -> int:
        return len(self._commands)

    def append(self, command: Command) -> None:
        """Record a command."""
        self._commands.append(command)

    def clear(self) -> None:
        """Drop all recorded commands."""
        self._commands.clear()

    def records(self) -> list[dict[str, Any]]:
        """Return the JSON-serializable description of every command, in order."""
        return [c.describe() for c in self._commands]

    def to_code(self, header: bool = True) -> str:
        """Generate a standalone matplotlib script reproducing all edits."""
        lines: list[str] = []
        if header:
            lines += [
                "# Generated by figmint. Reproduces the edited figure with plain matplotlib.",
                "import matplotlib.pyplot as plt",
                "",
            ]
        for command in self._commands:
            lines += command.to_code()
        return "\n".join(lines) + "\n"

    def to_project(self, *, mpl_version: str = "", figmint_version: str = "") -> str:
        """Serialize the log to a ``.figmint`` project document (JSON string)."""
        doc = {
            "schema": PROJECT_SCHEMA,
            "figmint_version": figmint_version,
            "mpl_version": mpl_version,
            "editlog": self.records(),
        }
        return json.dumps(doc, indent=2)

    @staticmethod
    def load_project(text: str) -> dict[str, Any]:
        """Parse a ``.figmint`` project document. Returns the raw dict.

        Replaying the edit log onto a reconstructed figure is done by the editor
        (it needs live artists); this only validates and returns the parsed document.
        """
        doc = json.loads(text)
        schema = doc.get("schema")
        if schema != PROJECT_SCHEMA:
            raise ValueError(f"Unsupported figmint project schema: {schema!r}")
        return doc
